// Code generated by generate_families.go; DO NOT EDIT.
// Source: families.ndjson

package main

var instanceTypes = []InstanceTypeInfo{
	{
		Name:   "m1",
		Year:   2006,
		Prefix: MainPrefix,
	},
	{
		Name:   "c1",
		Year:   2008,
		Prefix: CpuPrefix,
	},
	{
		Name:   "m2",
		Year:   2009,
		Prefix: MainPrefix,
	},
	{
		Name:   "cc1",
		Year:   2010,
		Prefix: ClusterComputePrefix,
	},
	{
		Name:   "t1",
		Year:   2010,
		Prefix: BurstPrefix,
	},
	{
		Name:   "cg1",
		Year:   2010,
		Prefix: GPUPrefix,
	},
	{
		Name:   "cc2",
		Year:   2011,
		Prefix: ClusterComputePrefix,
	},
	{
		Name:   "hi1",
		Year:   2012,
		Prefix: SSDPrefix,
	},
	{
		Name:   "m3",
		Year:   2012,
		Prefix: MainPrefix,
	},
	{
		Name:   "hs1",
		Year:   2012,
		Prefix: DenseHDDPrefix,
	},
	{
		Name:   "cr1",
		Year:   2013,
		Prefix: ClusterComputePrefix,
	},
	{
		Name:   "c3",
		Year:   2013,
		Prefix: CpuPrefix,
	},
	{
		Name:   "g2",
		Year:   2013,
		Prefix: GPUPrefix,
	},
	{
		Name:   "i2",
		Year:   2013,
		Prefix: SSDPrefix,
	},
	{
		Name:   "r3",
		Year:   2014,
		Prefix: MemMorePrefix,
	},
	{
		Name:   "t2",
		Year:   2014,
		Prefix: BurstPrefix,
	},
	{
		Name:   "c4",
		Year:   2015,
		Prefix: CpuPrefix,
	},
	{
		Name:   "d2",
		Year:   2015,
		Prefix: DenseHDDPrefix,
	},
	{
		Name:   "m4",
		Year:   2015,
		Prefix: MainPrefix,
	},
	{
		Name:   "x1",
		Year:   2016,
		Prefix: MemXtremePrefix,
	},
	{
		Name:   "p2",
		Year:   2016,
		Prefix: GPUPrefix,
	},
	{
		Name:   "f1",
		Year:   2016,
		Prefix: FPGAPrefix,
	},
	{
		Name:   "r4",
		Year:   2016,
		Prefix: MemMorePrefix,
	},
	{
		Name:   "i3",
		Year:   2016,
		Prefix: SSDPrefix,
	},
	{
		Name:   "c5",
		Year:   2016,
		Prefix: CpuPrefix,
	},
	{
		Name:   "g3",
		Year:   2017,
		Prefix: GPUPrefix,
	},
	{
		Name:   "x1e",
		Year:   2017,
		Prefix: MemXtremePrefix,
	},
	{
		Name:   "p3",
		Year:   2017,
		Prefix: GPUPrefix,
	},
	{
		Name:   "m5",
		Year:   2017,
		Prefix: MainPrefix,
	},
	{
		Name:   "h1",
		Year:   2017,
		Prefix: DenseHDDPrefix,
	},
	{
		Name:   "c5d",
		Year:   2018,
		Prefix: CpuPrefix,
		Flags:  NVMeSuffix,
	},
	{
		Name:   "m5d",
		Year:   2018,
		Prefix: MainPrefix,
		Flags:  NVMeSuffix,
	},
	{
		Name:   "z1d",
		Year:   2018,
		Prefix: HighFreqPrefix,
	},
	{
		Name:   "r5",
		Year:   2018,
		Prefix: MemMorePrefix,
	},
	{
		Name:   "t3",
		Year:   2018,
		Prefix: BurstPrefix,
	},
	{
		Name:   "g3s",
		Year:   2018,
		Prefix: GPUPrefix,
	},
	{
		Name:   "m5a",
		Year:   2018,
		Prefix: MainPrefix,
		Flags:  AmdSuffix,
	},
	{
		Name:   "r5a",
		Year:   2018,
		Prefix: MemMorePrefix,
		Flags:  AmdSuffix,
	},
	{
		Name:   "c5n",
		Year:   2018,
		Prefix: CpuPrefix,
		Flags:  NetworkSuffix,
	},
	{
		Name:   "a1",
		Year:   2018,
		Prefix: ArmPrefix,
	},
	{
		Name:   "p3dn",
		Year:   2018,
		Prefix: GPUPrefix,
		Flags:  NVMeSuffix | NetworkSuffix,
	},
	{
		Name:   "g4",
		Year:   2019,
		Prefix: GPUPrefix,
	},
	{
		Name:   "m5ad",
		Year:   2019,
		Prefix: MainPrefix,
		Flags:  AmdSuffix | NVMeSuffix,
	},
	{
		Name:   "r5d",
		Year:   2019,
		Prefix: MemMorePrefix,
		Flags:  NVMeSuffix,
	},
	{
		Name:   "r5ad",
		Year:   2019,
		Prefix: MemMorePrefix,
		Flags:  AmdSuffix | NVMeSuffix,
	},
	{
		Name:   "i3en",
		Year:   2019,
		Prefix: SSDPrefix,
		Flags:  NetworkSuffix,
	},
	{
		Name:   "g4dn",
		Year:   2019,
		Prefix: GPUPrefix,
		Flags:  GpuNvidiaSuffix,
	},
	{
		Name:   "r5dn",
		Year:   2019,
		Prefix: MemMorePrefix,
		Flags:  NVMeSuffix | NetworkSuffix,
	},
	{
		Name:   "r5n",
		Year:   2019,
		Prefix: MemMorePrefix,
		Flags:  NetworkSuffix,
	},
	{
		Name:   "m5dn",
		Year:   2019,
		Prefix: MainPrefix,
		Flags:  NVMeSuffix | NetworkSuffix,
	},
	{
		Name:   "m5n",
		Year:   2019,
		Prefix: MainPrefix,
		Flags:  NetworkSuffix,
	},
	{
		Name:   "inf1",
		Year:   2019,
		Prefix: InferencePrefix,
	},
	{
		Name:   "t3a",
		Year:   2019,
		Prefix: BurstPrefix,
		Flags:  AmdSuffix,
	},
	{
		Name:   "c5a",
		Year:   2020,
		Prefix: CpuPrefix,
		Flags:  AmdSuffix,
	},
	{
		Name:   "c5ad",
		Year:   2020,
		Prefix: CpuPrefix,
		Flags:  AmdSuffix | NVMeSuffix,
	},
	{
		Name:   "c6g",
		Year:   2020,
		Prefix: CpuPrefix,
		Flags:  GravitonSuffix,
	},
	{
		Name:   "c6gn",
		Year:   2020,
		Prefix: CpuPrefix,
		Flags:  GravitonSuffix | NetworkSuffix,
	},
	{
		Name:   "c6gd",
		Year:   2020,
		Prefix: CpuPrefix,
		Flags:  GravitonSuffix | NVMeSuffix,
	},
	{
		Name:   "d3",
		Year:   2020,
		Prefix: DenseHDDPrefix,
	},
	{
		Name:   "d3en",
		Year:   2020,
		Prefix: DenseHDDPrefix,
		Flags:  NetworkSuffix,
	},
	{
		Name:   "g4ad",
		Year:   2020,
		Prefix: GPUPrefix,
		Flags:  GpuAmdSuffix,
	},
	{
		Name:   "m5zn",
		Year:   2020,
		Prefix: MainPrefix,
		Flags:  HighFreqSuffix | NetworkSuffix,
	},
	{
		Name:   "m6g",
		Year:   2020,
		Prefix: MainPrefix,
		Flags:  GravitonSuffix,
	},
	{
		Name:   "m6gn",
		Year:   2020,
		Prefix: MainPrefix,
		Flags:  GravitonSuffix | NetworkSuffix,
	},
	{
		Name:   "p4d",
		Year:   2020,
		Prefix: GPUPrefix,
		Flags:  NVMeSuffix,
	},
	{
		Name:   "r5b",
		Year:   2020,
		Prefix: MemMorePrefix,
		Flags:  EBSOptimizedSuffix,
	},
	{
		Name:   "r6g",
		Year:   2020,
		Prefix: MemMorePrefix,
		Flags:  GravitonSuffix,
	},
	{
		Name:   "r6gd",
		Year:   2020,
		Prefix: MemMorePrefix,
		Flags:  GravitonSuffix | NVMeSuffix,
	},
	{
		Name:   "t4g",
		Year:   2020,
		Prefix: BurstPrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-x2gd-instances-graviton2-power-for-memory-intensive-workloads/
		Name:   "x2gd",
		Year:   2021,
		Prefix: MemXtremePrefix,
		Flags:  GravitonSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-m6i-instances-powered-by-the-latest-generation-intel-xeon-scalable-processors/
		Name:   "m6i",
		Year:   2022,
		Prefix: MainPrefix,
		Flags:  IntelSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-ec2-vt1-instances-video-transcoding/
		Name:   "vt1",
		Year:   2021,
		Prefix: VideoTranscodingPrefix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-c6i-instances-powered-by-the-latest-generation-intel-xeon-scalable-processors/
		Name:   "c6i",
		Year:   2022,
		Prefix: CpuPrefix,
		Flags:  IntelSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-ec2-instances-g5-with-nvidia-a10g-tensor-core-gpus/
		Name:   "g5",
		Year:   2021,
		Prefix: GPUPrefix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-r6i-memory-optimized-instances-powered-by-the-latest-generation-intel-xeon-scalable-processors/
		Name:   "r6i",
		Year:   2021,
		Prefix: MemMorePrefix,
		Flags:  IntelSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-m6a-instances-powered-by-3rd-gen-amd-epyc-processors/
		Name:   "m6a",
		Year:   2021,
		Prefix: MainPrefix,
		Flags:  AmdSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-g5g-instances-powered-by-aws-graviton2-processors-and-nvidia-t4g-tensor-core-gpus/
		Name:   "g5g",
		Year:   2021,
		Prefix: GPUPrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/join-the-preview-amazon-ec2-c7g-instances-powered-by-new-aws-graviton3-processors/
		// graviton 3
		Name:   "c7g",
		Year:   2021,
		Prefix: CpuPrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-storage-optimized-amazon-ec2-instances-im4gn-and-is4gen-powered-by-aws-graviton2-processors/
		Name:   "im4gn",
		Year:   2021,
		Prefix: SSDPrefix,
		Flags:  GravitonSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-storage-optimized-amazon-ec2-instances-im4gn-and-is4gen-powered-by-aws-graviton2-processors/
		Name:   "is4gn",
		Year:   2021,
		Prefix: SSDPrefix,
		Flags:  GravitonSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-ec2-trn1-instances/
		// trn:"Trainium"
		Name:   "trn1",
		Year:   2021,
		Prefix: InferencePrefix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-hpc6a-instance-optimized-for-high-performance-computing/
		Name:   "hpc6a",
		Year:   2022,
		Prefix: HPCPrefix,
		Flags:  AmdSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-x2iezn-instances-powered-by-the-fastest-intel-xeon-scalable-cpu-for-memory-intensive-workloads/
		Name:   "x2iezn",
		Year:   2022,
		Prefix: XeonScalablePrefix,
		Flags:  IntelSuffix | ExtendedMemorySuffix | HighFreqSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-c6a-instances-powered-by-3rd-gen-amd-epyc-processors-for-compute-intensive-workloads/
		Name:   "c6a",
		Year:   2022,
		Prefix: CpuPrefix,
		Flags:  AmdSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-x2idn-and-x2iedn-instances-for-memory-intensive-workloads-with-higher-network-bandwidth/
		Name:   "x2iedn",
		Year:   2022,
		Prefix: XeonScalablePrefix,
		Flags:  IntelSuffix | ExtendedMemorySuffix | NetworkSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-x2idn-and-x2iedn-instances-for-memory-intensive-workloads-with-higher-network-bandwidth/
		Name:   "x2idn",
		Year:   2022,
		Prefix: XeonScalablePrefix,
		Flags:  IntelSuffix | NetworkSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-storage-optimized-amazon-ec2-instances-i4i-powered-by-intel-xeon-scalable-ice-lake-processors/
		Name:   "i4i",
		Year:   2022,
		Prefix: SSDPrefix,
		Flags:  IntelSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2022/05/amazon-ec2-p4de-gpu-instances-ml-training-hpc/
		Name:   "p4de",
		Year:   2022,
		Prefix: GPUPrefix,
		Flags:  NVMeSuffix | ExtendedMemorySuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-m6id-and-c6id-instances-with-up-to-7-6-tb-local-nvme-storage/
		Name:   "c6id",
		Year:   2022,
		Prefix: CpuPrefix,
		Flags:  IntelSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-m6id-and-c6id-instances-with-up-to-7-6-tb-local-nvme-storage/
		Name:   "m6id",
		Year:   2022,
		Prefix: MainPrefix,
		Flags:  IntelSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-r6id-instances/
		Name:   "r6id",
		Year:   2022,
		Prefix: MemMorePrefix,
		Flags:  IntelSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-r6a-instances-powered-by-3rd-gen-amd-epyc-processors-for-memory-intensive-workloads/
		Name:   "r6a",
		Year:   2022,
		Prefix: MemMorePrefix,
		Flags:  AmdSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2022/11/introducing-amazon-ec2-r7iz-instances/
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-instance-types-in-the-works-c7gn-r7iz-and-hpc7g/
		Name:   "r7iz",
		Year:   2022,
		Prefix: MemMorePrefix,
		Flags:  IntelSuffix | HighFreqSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-m6id-and-c6id-instances-with-up-to-7-6-tb-local-nvme-storage/
		Name:   "m6in",
		Year:   2022,
		Prefix: MainPrefix,
		Flags:  IntelSuffix | NetworkSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-m6id-and-c6id-instances-with-up-to-7-6-tb-local-nvme-storage/
		Name:   "m6idn",
		Year:   2022,
		Prefix: MainPrefix,
		Flags:  IntelSuffix | NVMeSuffix | NetworkSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-m6id-and-c6id-instances-with-up-to-7-6-tb-local-nvme-storage/
		Name:   "c6in",
		Year:   2022,
		Prefix: CpuPrefix,
		Flags:  IntelSuffix | NetworkSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-m6id-and-c6id-instances-with-up-to-7-6-tb-local-nvme-storage/
		Name:   "r6in",
		Year:   2022,
		Prefix: MemMorePrefix,
		Flags:  IntelSuffix | NetworkSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-m6id-and-c6id-instances-with-up-to-7-6-tb-local-nvme-storage/
		Name:   "r6idn",
		Year:   2022,
		Prefix: MemMorePrefix,
		Flags:  IntelSuffix | NVMeSuffix | NetworkSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-instance-types-in-the-works-c7gn-r7iz-and-hpc7g/
		Name:   "c7gn",
		Year:   2022,
		Prefix: CpuPrefix,
		Flags:  GravitonSuffix | NetworkSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-instance-types-in-the-works-c7gn-r7iz-and-hpc7g/
		Name:   "hpc7g",
		Year:   2022,
		Prefix: HPCPrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-hpc6id-instances-optimized-for-high-performance-computing/
		Name:   "hpc6id",
		Year:   2022,
		Prefix: HPCPrefix,
		Flags:  IntelSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-graviton3-based-general-purpose-m7g-and-memory-optimized-r7g-amazon-ec2-instances
		Name:   "m7g",
		Year:   2023,
		Prefix: MainPrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-graviton3-based-general-purpose-m7g-and-memory-optimized-r7g-amazon-ec2-instances
		Name:   "r7g",
		Year:   2023,
		Prefix: MemMorePrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/amazon-ec2-inf2-instances-for-low-cost-high-performance-generative-ai-inference-are-now-generally-available/
		Name:   "inf2",
		Year:   2023,
		Prefix: InferencePrefix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-storage-optimized-amazon-ec2-i4g-instances-graviton-processors-and-aws-nitro-ssds/
		Name:   "i4g",
		Year:   2023,
		Prefix: SSDPrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-p5-instances-powered-by-nvidia-h100-tensor-core-gpus-for-accelerating-generative-ai-and-hpc-applications/
		Name:   "p5",
		Year:   2023,
		Prefix: GPUPrefix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-instances-c7gd-m7gd-and-r7gd-powered-by-aws-graviton3-processor-with-local-nvme-based-ssd-storage/
		Name:   "c7gd",
		Year:   2023,
		Prefix: CpuPrefix,
		Flags:  GravitonSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-instances-c7gd-m7gd-and-r7gd-powered-by-aws-graviton3-processor-with-local-nvme-based-ssd-storage/
		Name:   "m7gd",
		Year:   2023,
		Prefix: MainPrefix,
		Flags:  GravitonSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-instances-c7gd-m7gd-and-r7gd-powered-by-aws-graviton3-processor-with-local-nvme-based-ssd-storage/
		Name:   "r7gd",
		Year:   2023,
		Prefix: MemMorePrefix,
		Flags:  GravitonSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-seventh-generation-general-purpose-amazon-ec2-instances-m7i-flex-and-m7i/
		Name:   "m7i",
		Year:   2023,
		Prefix: MainPrefix,
		Flags:  IntelSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-seventh-generation-general-purpose-amazon-ec2-instances-m7i-flex-and-m7i/
		Name:   "m7i-flex",
		Year:   2023,
		Prefix: MainPrefix,
		Flags:  IntelSuffix | FlexSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-m7a-general-purpose-instances-powered-by-4th-gen-amd-epyc-processors/
		Name:   "m7a",
		Year:   2023,
		Prefix: MainPrefix,
		Flags:  AmdSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-hpc7a-instances-powered-by-4th-gen-amd-epyc-processors-optimized-for-high-performance-computing/
		Name:   "hpc7a",
		Year:   2023,
		Prefix: HPCPrefix,
		Flags:  AmdSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-r7a-instances-powered-by-4th-gen-amd-epyc-processors-for-memory-optimized-workloads/
		Name:   "r7a",
		Year:   2023,
		Prefix: MemMorePrefix,
		Flags:  AmdSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2023/09/amazon-ec2-c7i-instances/
		Name:   "c7i",
		Year:   2023,
		Prefix: CpuPrefix,
		Flags:  IntelSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-c7a-instances-powered-by-4th-gen-amd-epyc-processors-for-compute-optimized-workloads/
		Name:   "c7a",
		Year:   2023,
		Prefix: CpuPrefix,
		Flags:  AmdSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-ec2-r7i-instances/
		Name:   "r7i",
		Year:   2023,
		Prefix: MemMorePrefix,
		Flags:  IntelSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/introducing-amazon-ec2-high-memory-u7i-instances-for-large-in-memory-databases-preview/
		Name:   "u7i",
		Year:   2023,
		Prefix: MemUltraPrefix,
		Flags:  IntelSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/introducing-amazon-ec2-high-memory-u7i-instances-for-large-in-memory-databases-preview/
		Name:   "u7in",
		Year:   2023,
		Prefix: MemUltraPrefix,
		Flags:  IntelSuffix | NetworkSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/join-the-preview-for-new-memory-optimized-aws-graviton4-powered-amazon-ec2-instances-r8g/
		Name:   "r8g",
		Year:   2023,
		Prefix: MemMorePrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2024/04/general-availability-amazon-ec2-g6-instances/
		Name:   "g6",
		Year:   2024,
		Prefix: GPUPrefix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-compute-optimized-c7i-flex-amazon-ec2-flex-instances/
		Name:   "c7i-flex",
		Year:   2024,
		Prefix: CpuPrefix,
		Flags:  IntelSuffix | FlexSuffix,
	},
	{
		// https://aws.amazon.com/blogs/machine-learning/amazon-ec2-p5e-instances-are-generally-available/
		Name:   "p5e",
		Year:   2024,
		Prefix: GPUPrefix,
	},
	{
		// https://aws.amazon.com/blogs/aws/now-available-graviton4-powered-memory-optimized-amazon-ec2-x8g-instances/
		Name:   "x8g",
		Year:   2024,
		Prefix: MemXtremePrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/run-your-compute-intensive-and-general-purpose-workloads-sustainably-with-the-new-amazon-ec2-c8g-m8g-instances/
		Name:   "c8g",
		Year:   2024,
		Prefix: CpuPrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/run-your-compute-intensive-and-general-purpose-workloads-sustainably-with-the-new-amazon-ec2-c8g-m8g-instances/
		Name:   "m8g",
		Year:   2024,
		Prefix: MainPrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/now-available-storage-optimized-amazon-ec2-i7ie-instances/
		Name:   "i7ie",
		Year:   2024,
		Prefix: SSDPrefix,
		Flags:  IntelSuffix | ExtendedMemorySuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/introducing-storage-optimized-amazon-ec2-i8g-instances-powered-by-aws-graviton4-processors-and-3rd-gen-aws-nitro-ssds/
		Name:   "i8g",
		Year:   2024,
		Prefix: SSDPrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2024/12/amazon-ec2-p5en-instances-generative-ai-hpc-generally-available/
		Name:   "p5en",
		Year:   2024,
		Prefix: GPUPrefix,
		Flags:  NetworkSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/amazon-ec2-trn2-instances-and-trn2-ultraservers-for-aiml-training-and-inference-is-now-available/
		Name:   "trn2",
		Year:   2024,
		Prefix: InferencePrefix,
	},
	{
		// https://aws.amazon.com/blogs/aws/now-available-second-generation-fpga-powered-amazon-ec2-instances-f2/
		Name:   "f2",
		Year:   2024,
		Prefix: FPGAPrefix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-high-memory-u7inh-instance-on-hpe-server-for-large-in-memory-databases/
		Name:   "u7inh",
		Year:   2024,
		Prefix: MemUltraPrefix,
		Flags:  IntelSuffix | NetworkSuffix | HpeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-graviton4-based-instances-with-nvme-ssd-storage/
		Name:   "c8gd",
		Year:   2025,
		Prefix: CpuPrefix,
		Flags:  GravitonSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-graviton4-based-instances-with-nvme-ssd-storage/
		Name:   "m8gd",
		Year:   2025,
		Prefix: MainPrefix,
		Flags:  GravitonSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-graviton4-based-instances-with-nvme-ssd-storage/
		Name:   "r8gd",
		Year:   2025,
		Prefix: MemMorePrefix,
		Flags:  GravitonSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-c8gn-instances-powered-by-aws-graviton4-offering-up-to-600gbps-network-bandwidth/
		Name:   "c8gn",
		Year:   2025,
		Prefix: CpuPrefix,
		Flags:  GravitonSuffix | NetworkSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-amazon-ec2-p6e-gb200-ultraservers-powered-by-nvidia-grace-blackwell-gpus-for-the-highest-ai-performance/
		Name:   "p6e",
		Year:   2025,
		Prefix: GPUPrefix,
		Flags:  ExtendedMemorySuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/best-performance-and-fastest-memory-with-the-new-amazon-ec2-r8i-and-r8i-flex-instances/
		Name:   "r8i",
		Year:   2025,
		Prefix: MemMorePrefix,
		Flags:  IntelSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/best-performance-and-fastest-memory-with-the-new-amazon-ec2-r8i-and-r8i-flex-instances/
		Name:   "r8i-flex",
		Year:   2025,
		Prefix: MemMorePrefix,
		Flags:  IntelSuffix | FlexSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-general-purpose-amazon-ec2-m8i-and-m8i-flex-instances-are-now-available/
		Name:   "m8i",
		Year:   2025,
		Prefix: MainPrefix,
		Flags:  IntelSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-general-purpose-amazon-ec2-m8i-and-m8i-flex-instances-are-now-available/
		Name:   "m8i-flex",
		Year:   2025,
		Prefix: MainPrefix,
		Flags:  IntelSuffix | FlexSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2025/09/amazon-ec2-r8gb-instances/
		Name:   "r8gb",
		Year:   2025,
		Prefix: MemMorePrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/introducing-new-compute-optimized-amazon-ec2-c8i-and-c8i-flex-instances/
		Name:   "c8i",
		Year:   2025,
		Prefix: CpuPrefix,
		Flags:  IntelSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/introducing-new-compute-optimized-amazon-ec2-c8i-and-c8i-flex-instances/
		Name:   "c8i-flex",
		Year:   2025,
		Prefix: CpuPrefix,
		Flags:  IntelSuffix | FlexSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-general-purpose-amazon-ec2-m8a-instances-are-now-available/
		Name:   "m8a",
		Year:   2025,
		Prefix: MainPrefix,
		Flags:  AmdSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2025/11/memory-optimized-amazon-ec2-r8a-instances/
		Name:   "r8a",
		Year:   2025,
		Prefix: MemMorePrefix,
		Flags:  AmdSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/new-aws-billing-transfer-for-centrally-managing-aws-billing-and-costs-across-multiple-organizations/
		Name:   "P6-B300",
		Year:   2025,
		Prefix: GPUPrefix,
		Flags:  GpuNvidiaSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/introducing-amazon-ec2-x8aedz-instances-powered-by-5th-gen-amd-epyc-processors-for-memory-intensive-workloads/
		Name:   "x8aedz",
		Year:   2025,
		Prefix: MemXtremePrefix,
		Flags:  AmdSuffix | ExtendedMemorySuffix | NVMeSuffix | HighFreqSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2025/12/compute-optimized-amazon-ec2-c8a-instances/
		Name:   "c8a",
		Year:   2025,
		Prefix: CpuPrefix,
		Flags:  AmdSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2025/12/amazon-ec2-x8i-instances-preview/
		Name:   "x8i",
		Year:   2025,
		Prefix: MemXtremePrefix,
		Flags:  IntelSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2025/12/aws-amazon-ec2-m8azn-preview/
		Name:   "m8azn",
		Year:   2025,
		Prefix: MainPrefix,
		Flags:  AmdSuffix | HighFreqSuffix | NetworkSuffix,
	},
	{
		// https://aws.amazon.com/about-aws/whats-new/2025/12/ec2-m9g-instances-graviton5-processors-preview/
		Name:   "m9g",
		Year:   2025,
		Prefix: MainPrefix,
		Flags:  GravitonSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/announcing-amazon-ec2-g7e-instances-accelerated-by-nvidia-rtx-pro-6000-blackwell-server-edition-gpus/
		Name:   "g7e",
		Year:   2026,
		Prefix: GPUPrefix,
		Flags:  ExtendedMemorySuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/amazon-ec2-c8id-m8id-and-r8id-instances-with-up-to-22-8-tb-local-nvme-storage-are-generally-available/
		Name:   "c8id",
		Year:   2026,
		Prefix: CpuPrefix,
		Flags:  IntelSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/amazon-ec2-c8id-m8id-and-r8id-instances-with-up-to-22-8-tb-local-nvme-storage-are-generally-available/
		Name:   "m8id",
		Year:   2026,
		Prefix: MainPrefix,
		Flags:  IntelSuffix | NVMeSuffix,
	},
	{
		// https://aws.amazon.com/blogs/aws/amazon-ec2-c8id-m8id-and-r8id-instances-with-up-to-22-8-tb-local-nvme-storage-are-generally-available/
		Name:   "r8id",
		Year:   2026,
		Prefix: MemMorePrefix,
		Flags:  IntelSuffix | NVMeSuffix,
	},
}
