//go:build ignore

// Command generate_families builds families.go from families.ndjson.
//
// families.ndjson is the source of truth for the EC2 instance family table:
// one JSON object per line, e.g.
//
//	{"name":"c5d","year":2018,"prefix":"CpuPrefix","flags":["NVMeSuffix"],"url":"https://..."}
//
// "prefix" must be one of the InstanceCodePrefix constants and each entry in
// "flags" one of the InstanceCodeSuffix constants declared in main.go. To add a
// family, append a line to families.ndjson and run `go generate`.
package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

type entry struct {
	Name   string   `json:"name"`
	Year   int      `json:"year"`
	Prefix string   `json:"prefix"`
	Flags  []string `json:"flags,omitempty"`
	URL    string   `json:"url,omitempty"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "generate_families:", err)
		os.Exit(1)
	}
}

func run() error {
	prefixes, suffixes, err := validNames("main.go")
	if err != nil {
		return err
	}

	f, err := os.Open("families.ndjson")
	if err != nil {
		return err
	}
	defer f.Close()

	var entries []entry
	seen := make(map[string]bool)
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for line := 1; sc.Scan(); line++ {
		b := bytes.TrimSpace(sc.Bytes())
		if len(b) == 0 {
			continue
		}
		var e entry
		dec := json.NewDecoder(bytes.NewReader(b))
		dec.DisallowUnknownFields()
		if err := dec.Decode(&e); err != nil {
			return fmt.Errorf("line %d: %w", line, err)
		}
		if e.Name == "" {
			return fmt.Errorf("line %d: missing name", line)
		}
		if seen[e.Name] {
			return fmt.Errorf("line %d: duplicate name %q", line, e.Name)
		}
		seen[e.Name] = true
		if e.Year == 0 {
			return fmt.Errorf("line %d (%s): missing year", line, e.Name)
		}
		if !prefixes[e.Prefix] {
			return fmt.Errorf("line %d (%s): unknown prefix %q", line, e.Name, e.Prefix)
		}
		for _, fl := range e.Flags {
			if !suffixes[fl] {
				return fmt.Errorf("line %d (%s): unknown flag %q", line, e.Name, fl)
			}
		}
		entries = append(entries, e)
	}
	if err := sc.Err(); err != nil {
		return err
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by generate_families.go; DO NOT EDIT.\n")
	buf.WriteString("// Source: families.ndjson\n\n")
	buf.WriteString("package main\n\n")
	buf.WriteString("var instanceTypes = []InstanceTypeInfo{\n")
	for _, e := range entries {
		buf.WriteString("\t{\n")
		if e.URL != "" {
			for _, l := range strings.Split(e.URL, "\n") {
				fmt.Fprintf(&buf, "\t\t// %s\n", l)
			}
		}
		fmt.Fprintf(&buf, "\t\tName:   %q,\n", e.Name)
		fmt.Fprintf(&buf, "\t\tYear:   %d,\n", e.Year)
		fmt.Fprintf(&buf, "\t\tPrefix: %s,\n", e.Prefix)
		if len(e.Flags) > 0 {
			fmt.Fprintf(&buf, "\t\tFlags:  %s,\n", strings.Join(e.Flags, " | "))
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w", err)
	}
	return os.WriteFile("families.go", src, 0644)
}

// validNames parses path and returns the sets of declared InstanceCodePrefix
// and InstanceCodeSuffix constant names, so families.ndjson can be validated
// against the actual definitions rather than a hand-maintained copy.
func validNames(path string) (prefixes, suffixes map[string]bool, err error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, nil, err
	}

	prefixes = make(map[string]bool)
	suffixes = make(map[string]bool)
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		var typ string // carries across iota blocks where only the first spec is typed
		for _, spec := range gd.Specs {
			vs := spec.(*ast.ValueSpec)
			if id, ok := vs.Type.(*ast.Ident); ok {
				typ = id.Name
			}
			for _, name := range vs.Names {
				switch typ {
				case "InstanceCodePrefix":
					prefixes[name.Name] = true
				case "InstanceCodeSuffix":
					suffixes[name.Name] = true
				}
			}
		}
	}
	if len(prefixes) == 0 || len(suffixes) == 0 {
		return nil, nil, fmt.Errorf("no prefix/suffix constants found in %s", path)
	}
	return prefixes, suffixes, nil
}
